'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property Id As Integer
    Public Property ProductId As String
    Public Property ProductName As String
    Public Property Description As String
    Public Property Category As String
    Public Property Subcategory As String
    Public Property Version As String
    Public Property LaunchDate As Nullable(Of Date)
    Public Property Price As Nullable(Of Decimal)
    Public Property ImgID As Nullable(Of System.Guid)
    Public Property Extension As String
    Public Property FileName As String

End Class
