'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property ID As Integer
    Public Property Name As String
    Public Property TimeZone As String
    Public Property Status As String
    Public Property SharedLogin As String
    Public Property Email As String
    Public Property MobileNumber As String
    Public Property Streat As String
    Public Property City As String
    Public Property PinCode As Nullable(Of Integer)
    Public Property Country As String

    Public Overridable Property UserRolesMappings As ICollection(Of UserRolesMapping) = New HashSet(Of UserRolesMapping)

End Class
